### ISSUE TITLE
make the list of PlantUML "Features" more fair

### ISSUE THREAD

**Issue by VladimirAlexiev** [terrastruct/text-to-diagram-site#49]
Continuing #40 , I looked at the list **Features** at the bottom of https://text-to-diagram.com/?b=plantuml.
Here are my comments on features marked as not supported by PlantUML

- Friendly error messages: Not just "syntax error"
  True, but it shows the exact error location
- Images & Icons: What are the available options for including images and icons: Any URL
  - It has some HTML tags, including `<img>` that lets you use any URL as image: https://plantuml.com/creole#f42f1366d9ab93bb.
  - In addition, it has a very wide set of icons (https://plantuml.com/openiconic), unicode emojis (https://plantuml.com/unicode and https://plantuml.com/creole#68305e25f5788db0) and sprites (https://plantuml.com/sprite and https://plantuml.com/stdlib)
- Markdown: Use Markdown for text objects in the diagram	
  True, but it has https://plantuml.com/creole which is just about the same
- LaTeX: Render math equations suitable for academic usage
  Yes, see https://plantuml.com/ascii-math
- Native Github rendering: Does it render natively on Github:
  I guess that depends on plugins and addons. Eg for me, neither https://github.com/terrastruct/d2/blob/master/docs/flow.d2 nor https://github.dev/terrastruct/d2/blob/master/docs/flow.d2 are rendered, but PlantUML is rendered using https://chrome.google.com/webstore/detail/plantuml-visualizer/ffaloebcmkogfdkemcekamlmfkkmgkcf (eg see diagrams below)
- Code snippets: Render syntax-highlighted code snippets
  PlantUML supports code snippets, see https://plantuml.com/creole#ca0dbad92a874b2f, but currently not code highlighting.
  Then again, who wants a lot of code in a *diagram*?
- Responsive dark mode: Can the diagram render with both light and dark mode, switching depending on user preference.
  Yes, there is at http://www.plantuml.com/plantuml/ (the next URL token is `uml` for light mode, `duml` for dark) 
![image](https://github.com/terrastruct/text-to-diagram-site/assets/536250/8f76f42e-8358-49ea-8d64-daefdf23f520)
- PDF exports: Can the CLI export PDF output: 
  It only requires adding some jars: https://plantuml.com/pdf

In addition:
- you should not use square brackets in nodes (eg `[foo]` in https://text-to-diagram.com/?b=plantuml&example=containers because these get rendered as "components" with an interface icon, not simple rectangles
- PlantUML supports a large number of non-UML diagrams, see https://plantuml.com/

**Comment by VladimirAlexiev** [comment]
Here is a fixed diagram for https://text-to-diagram.com/?b=plantuml&example=text .
`Compile error: PlantUML does not support rich text` is a very unfair statement.
The only think I couldn't do is include quotes in the text, since that's used to delimit the text

```plantuml
@startuml
rectangle description as "
== Hope is a good breakfast, but it is a bad supper

* Look into my eyes and try to forget that you have a Macy's charge card!
* The **Tree of Learning** bears the noblest fruit, but noble fruit tastes bad.

  There is nothing new under the sun, but there are lots of old things we don't know yet

* //Ambrose Bierce//
"

rectangle x

description -> x
@enduml
```

**Comment by chainofreasoning** [comment]
@VladimirAlexiev Thanks for continuing #40  the comparisons with more sample fixes.  At that time I was evaluating text-to-diagram technologies for several commercial projects. ( I feel we have to  have to fund and participate in open source to keep it thriving).  I am starting yet another effort and I am updating my knowledge of available technologies again.   After such a period of time since the first report in #40, I am very disappointed to see the  false and bias information still present.  It is simply not necessary as there are valid critiques of PlantUML.  The comparisons information could be easily fixed.  I do not plan to recommend this project to my colleagues any further.

**Comment by alixander** [comment]
Thanks @VladimirAlexiev , I will include next time I update this.

@chainofreasoning [your report](https://github.com/terrastruct/text-to-diagram-site/pull/42#issuecomment-1474620741) is the length of a small tutorial. I am the only one that maintains this on top of many other repositories. I've just not had the time. D2 has undergone many changes and I have not updated it either since 2023. If you'd like to submit a PR, you're welcome to. If you'd like to "fund and participate in open source", you're welcome to.

**Comment by chainofreasoning** [comment]
We can all understand being overburdened, rearranging priorities, and such.  Happens to us all and is easily forgivable.  The fact remains the public information is incorrect and needlessly defamatory towards another open source project.   Your snide remarks will not change that.  As a community we can do better.  We tried to do the first passes at helping with examples and fixes.  I am sorry if you found the issue report to long but I err on more details with issue reports dealing with runtime errors across platforms.   I am "welcomed" to do what I want with my time as anyone else.  Leaving this issue is what I choose to do.

**Comment by alixander** [comment]
@chainofreasoning I make an earnest effort to be correct in comparisons, so I appreciate issue reports like these (and yours). It's also why this effort is public, so that corrections can easily be spotted and made. As for your issue, it's not that it's detailed that I'm pointing out -- I appreciate the detail. It's that it's not easily addressable, there's time and effort involved. Please refrain from insults like calling this project defamatory, otherwise I'll have to block you.

**Comment by alixander** [comment]
> Friendly error messages: Not just "syntax error"
> True, but it shows the exact error location

Comparison stands.

> Images & Icons: What are the available options for including images and icons: Any URL
> It has some HTML tags, including <img> that lets you use any URL as image: https://plantuml.com/creole#f42f1366d9ab93bb.
> In addition, it has a very wide set of icons (https://plantuml.com/openiconic), unicode emojis (https://plantuml.com/unicode and https://plantuml.com/creole#68305e25f5788db0) and sprites (https://plantuml.com/sprite and https://plantuml.com/stdlib)

Updated to say PlantUML can load any url.

> Markdown: Use Markdown for text objects in the diagram
> True, but it has https://plantuml.com/creole which is just about the same

It's not. Markdown is highly standardized. It's like saying Bash is the same Python or something.

> LaTeX: Render math equations suitable for academic usage
> Yes, see https://plantuml.com/ascii-math

Fair, updated to say PlantUML supports this.

> Native Github rendering: Does it render natively on Github:
> I guess that depends on plugins and addons. Eg for me, neither https://github.com/terrastruct/d2/blob/master/docs/flow.d2 nor https://github.dev/terrastruct/d2/blob/master/docs/flow.d2 are rendered, but PlantUML is rendered using https://chrome.google.com/webstore/detail/plantuml-visualizer/ffaloebcmkogfdkemcekamlmfkkmgkcf (eg see diagrams below)

That's not what native means.

> Code snippets: Render syntax-highlighted code snippets
> PlantUML supports code snippets, see https://plantuml.com/creole#ca0dbad92a874b2f, but currently not code highlighting.
> Then again, who wants a lot of code in a diagram?

Without syntax highlighting, code snippets are just monospaced text? Point stands.

> Responsive dark mode: Can the diagram render with both light and dark mode, switching depending on user preference.
> Yes, there is at http://www.plantuml.com/plantuml/ (the next URL token is uml for light mode, duml for dark)
> image

That's not what responsive means.

> PDF exports: Can the CLI export PDF output:
> It only requires adding some jars: https://plantuml.com/pdf

Updated to say "with additional installs".

> you should not use square brackets in nodes (eg [foo] in https://text-to-diagram.com/?b=plantuml&example=containers because these get rendered as "components" with an interface icon, not simple rectangles

I tried it. This doesn't work.

```
@startuml

node "parent" {
  node "childB" {
    grandchild
  }
  childA -> grandchild
}

foo -> childA

@enduml
```

<img width="202" alt="Screenshot 2024-09-03 at 12 17 10 PM" src="https://github.com/user-attachments/assets/a88972dd-eece-42b2-b15b-bf040592020a">

**Comment by Potherca** [comment]
Hi @alixander! Great work with going through all the items on that list. Very much appreciated!

One minor point, regarding the grandchild item, it looks like there's a keyword missing (i.e. something that tells PlantUML what type/shape the element should be). With that added, the example works fine:
<table><tr><td>

```plantuml
@startuml
node "parent" {
  node "childB" {
    node grandchild /' <-- there was a "node" keyword missing there '/
  }
  childA -> grandchild
}

foo -> childA
@enduml
```
</td><td>

[![](https://www.plantuml.com/plantuml/png/SoWkIImgAStDuUBAoqz9LL0gI2nApIjHKgZcKb20Y2HdPEQaE454e6BfHObvAM1ne5Wj48FPZWgwTiXIjLnSQVdvG46eD1UNGsfU2j0k0000)][1]

</td></tr></table>

For [shits and giggles][2], here's a diagram [from the manual][3] with every shape nested:

[![](https://www.plantuml.com/plantuml/png/XP1R3eGW34N_kueknQrqe3f6f0wFP99czZuLHJyDoJdtGWAaGowKIbq3a2kpH3obODlpQ0sleE0eUMom7AHQQRGcwoQHOy4xANWgzABCU0M5SGwC3PObU4vuodgYrGuR5TxyfSd-qgqGnJCsA6pa5feOksqdYUESiLlXKxao7bH8x0h5oLw-au8Dm2ruS6-Izjkw5NwFQ-3ezmd-0G00)][4]

[1]: https://www.plantuml.com/plantuml/png/SoWkIImgAStDuUBAoqz9LL0gI2nApIjHKgZcKb20Y2HdPEQaE454e6BfHObvAM1ne5Wj48FPZWgwTiXIjLnSQVdvG46eD1UNGsfU2j0k0000
[2]: https://en.wiktionary.org/wiki/for_shits_and_giggles
[3]: https://plantuml.com/deployment-diagram#b2ecd56c45d3d896
[4]: https://www.plantuml.com/plantuml/uml/XP1R3eGW34N_kueknQrqe3f6f0wFP99czZuLHJyDoJdtGWAaGowKIbq3a2kpH3obODlpQ0sleE0eUMom7AHQQRGcwoQHOy4xANWgzABCU0M5SGwC3PObU4vuodgYrGuR5TxyfSd-qgqGnJCsA6pa5feOksqdYUESiLlXKxao7bH8x0h5oLw-au8Dm2ruS6-Izjkw5NwFQ-3ezmd-0G00
